//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCollection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieCollection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists!.
        /// </summary>
        internal static string AddUserAlreadExistsCaption {
            get {
                return ResourceManager.GetString("AddUserAlreadExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected username is already in use!.
        /// </summary>
        internal static string AddUserAlreadExistsText {
            get {
                return ResourceManager.GetString("AddUserAlreadExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string AddUserAlreadExistsTitle {
            get {
                return ResourceManager.GetString("AddUserAlreadExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new User....
        /// </summary>
        internal static string AddUserHeader {
            get {
                return ResourceManager.GetString("AddUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Name of the new User:.
        /// </summary>
        internal static string AddUserText {
            get {
                return ResourceManager.GetString("AddUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto select if only one Result.
        /// </summary>
        internal static string AutoSelectIfOnlyOne {
            get {
                return ResourceManager.GetString("AutoSelectIfOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Movie.
        /// </summary>
        internal static string ButtonAddMovie {
            get {
                return ResourceManager.GetString("ButtonAddMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for new file....
        /// </summary>
        internal static string ButtonBrowseToolTip {
            get {
                return ResourceManager.GetString("ButtonBrowseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete including Media-Files.
        /// </summary>
        internal static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Movie(s).
        /// </summary>
        internal static string ButtonRemoveMovie {
            get {
                return ResourceManager.GetString("ButtonRemoveMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search online....
        /// </summary>
        internal static string ButtonWebSearch {
            get {
                return ResourceManager.GetString("ButtonWebSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1080p.
        /// </summary>
        internal static string CheckBox1080p {
            get {
                return ResourceManager.GetString("CheckBox1080p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720p.
        /// </summary>
        internal static string CheckBox720p {
            get {
                return ResourceManager.GetString("CheckBox720p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non HD.
        /// </summary>
        internal static string CheckBoxNonHD {
            get {
                return ResourceManager.GetString("CheckBoxNonHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string CheckBoxResolution {
            get {
                return ResourceManager.GetString("CheckBoxResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        internal static string CheckBoxSeen {
            get {
                return ResourceManager.GetString("CheckBoxSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to ignore.
        /// </summary>
        internal static string CheckBoxSeenFilterToolTip {
            get {
                return ResourceManager.GetString("CheckBoxSeenFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an Error while deleting the Mediafile!.
        /// </summary>
        internal static string DeleteMovieErrorMain {
            get {
                return ResourceManager.GetString("DeleteMovieErrorMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exception occured while deleting &apos;{0}&apos;..
        /// </summary>
        internal static string DeleteMovieErrorText {
            get {
                return ResourceManager.GetString("DeleteMovieErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleteing Mediafile.
        /// </summary>
        internal static string DeleteMovieErrorTitle {
            get {
                return ResourceManager.GetString("DeleteMovieErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the selected movies?.
        /// </summary>
        internal static string DeleteMoviesCaption {
            get {
                return ResourceManager.GetString("DeleteMoviesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete associated Mediafiles.
        /// </summary>
        internal static string DeleteMoviesCheckBox {
            get {
                return ResourceManager.GetString("DeleteMoviesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This action can&apos;t be undo!.
        /// </summary>
        internal static string DeleteMoviesFooter {
            get {
                return ResourceManager.GetString("DeleteMoviesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure you want to delete the {0} selected movies?.
        /// </summary>
        internal static string DeleteMoviesText {
            get {
                return ResourceManager.GetString("DeleteMoviesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete movies?.
        /// </summary>
        internal static string DeleteMoviesTitle {
            get {
                return ResourceManager.GetString("DeleteMoviesTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DivX {
            get {
                object obj = ResourceManager.GetObject("DivX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dolby_digital {
            get {
                object obj = ResourceManager.GetObject("dolby_digital", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DTS {
            get {
                object obj = ResourceManager.GetObject("DTS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DVD {
            get {
                object obj = ResourceManager.GetObject("DVD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        internal static string ExpanderCast {
            get {
                return ResourceManager.GetString("ExpanderCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string ExpanderFilter {
            get {
                return ResourceManager.GetString("ExpanderFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string ExpanderGenre {
            get {
                return ResourceManager.GetString("ExpanderGenre", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FullHD {
            get {
                object obj = ResourceManager.GetObject("FullHD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_arrow1 {
            get {
                object obj = ResourceManager.GetObject("green_arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_arrow2 {
            get {
                object obj = ResourceManager.GetObject("green_arrow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media File.
        /// </summary>
        internal static string GroupBoxMediaFile {
            get {
                return ResourceManager.GetString("GroupBoxMediaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        internal static string GroupBoxUserSettings {
            get {
                return ResourceManager.GetString("GroupBoxUserSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap h264 {
            get {
                object obj = ResourceManager.GetObject("h264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HD {
            get {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change / Right-Click to remove....
        /// </summary>
        internal static string ImageCover {
            get {
                return ResourceManager.GetString("ImageCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.jpg;*.jpeg;*.png;*.gif.
        /// </summary>
        internal static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string ImagesFilterText {
            get {
                return ResourceManager.GetString("ImagesFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Actor.
        /// </summary>
        internal static string InputBoxAddCastDefaultPerson {
            get {
                return ResourceManager.GetString("InputBoxAddCastDefaultPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputBoxAddCastDefaultRole {
            get {
                return ResourceManager.GetString("InputBoxAddCastDefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new Actor:.
        /// </summary>
        internal static string InputBoxAddCastPromtPerson {
            get {
                return ResourceManager.GetString("InputBoxAddCastPromtPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the role of the Actor (leave blank if unknown):.
        /// </summary>
        internal static string InputBoxAddCastPromtRole {
            get {
                return ResourceManager.GetString("InputBoxAddCastPromtRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Actor.
        /// </summary>
        internal static string InputBoxAddCastTitlePerson {
            get {
                return ResourceManager.GetString("InputBoxAddCastTitlePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role of the new Actor.
        /// </summary>
        internal static string InputBoxAddCastTitleRole {
            get {
                return ResourceManager.GetString("InputBoxAddCastTitleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Genre.
        /// </summary>
        internal static string InputBoxAddGenreDefault {
            get {
                return ResourceManager.GetString("InputBoxAddGenreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new Genre:.
        /// </summary>
        internal static string InputBoxAddGenrePromt {
            get {
                return ResourceManager.GetString("InputBoxAddGenrePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Genre.
        /// </summary>
        internal static string InputBoxAddGenreTitle {
            get {
                return ResourceManager.GetString("InputBoxAddGenreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio:.
        /// </summary>
        internal static string LabelAudio {
            get {
                return ResourceManager.GetString("LabelAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast:.
        /// </summary>
        internal static string LabelCast {
            get {
                return ResourceManager.GetString("LabelCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string LabelComment {
            get {
                return ResourceManager.GetString("LabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director:.
        /// </summary>
        internal static string LabelDirector {
            get {
                return ResourceManager.GetString("LabelDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        internal static string LabelGenre {
            get {
                return ResourceManager.GetString("LabelGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string LabelImporting {
            get {
                return ResourceManager.GetString("LabelImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening....
        /// </summary>
        internal static string LabelOpening {
            get {
                return ResourceManager.GetString("LabelOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title:.
        /// </summary>
        internal static string LabelOriginalTitle {
            get {
                return ResourceManager.GetString("LabelOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        internal static string LabelRating {
            get {
                return ResourceManager.GetString("LabelRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string LabelSearching {
            get {
                return ResourceManager.GetString("LabelSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video:.
        /// </summary>
        internal static string LabelVideo {
            get {
                return ResourceManager.GetString("LabelVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string LabelYear {
            get {
                return ResourceManager.GetString("LabelYear", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap lang_icon {
            get {
                object obj = ResourceManager.GetObject("lang_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.mkv;*.avi;*.ifo;*.mpg;*.mpeg;*.divx;*.ts;*.ratDVD.
        /// </summary>
        internal static string MediaFilter {
            get {
                return ResourceManager.GetString("MediaFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Files.
        /// </summary>
        internal static string MediaFilterText {
            get {
                return ResourceManager.GetString("MediaFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new User....
        /// </summary>
        internal static string MenuItemAddUser {
            get {
                return ResourceManager.GetString("MenuItemAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced List View.
        /// </summary>
        internal static string MenuItemAdvancedView {
            get {
                return ResourceManager.GetString("MenuItemAdvancedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string MenuItemImport {
            get {
                return ResourceManager.GetString("MenuItemImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        internal static string MenuItemImportFile {
            get {
                return ResourceManager.GetString("MenuItemImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder....
        /// </summary>
        internal static string MenuItemImportFolder {
            get {
                return ResourceManager.GetString("MenuItemImportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuItemLanguage {
            get {
                return ResourceManager.GetString("MenuItemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MenuItemNew {
            get {
                return ResourceManager.GetString("MenuItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string MenuItemOpen {
            get {
                return ResourceManager.GetString("MenuItemOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Databases.
        /// </summary>
        internal static string MenuItemPlugins {
            get {
                return ResourceManager.GetString("MenuItemPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tool-Tip.
        /// </summary>
        internal static string MenuItemShowToolTip {
            get {
                return ResourceManager.GetString("MenuItemShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Year.
        /// </summary>
        internal static string MenuItemShowYear {
            get {
                return ResourceManager.GetString("MenuItemShowYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple List View.
        /// </summary>
        internal static string MenuItemSimpleView {
            get {
                return ResourceManager.GetString("MenuItemSimpleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string MenuItemUser {
            get {
                return ResourceManager.GetString("MenuItemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MenuItemView {
            get {
                return ResourceManager.GetString("MenuItemView", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MKV {
            get {
                object obj = ResourceManager.GetObject("MKV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mp3 {
            get {
                object obj = ResourceManager.GetObject("mp3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mpeg {
            get {
                object obj = ResourceManager.GetObject("mpeg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Movie.
        /// </summary>
        internal static string NewMovieDefaultTitle {
            get {
                return ResourceManager.GetString("NewMovieDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening the {0}!.
        /// </summary>
        internal static string OpeningLine1 {
            get {
                return ResourceManager.GetString("OpeningLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Source: &apos;{0}&apos;.
        /// </summary>
        internal static string OpeningLine2 {
            get {
                return ResourceManager.GetString("OpeningLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Movies.
        /// </summary>
        internal static string StatusBarInfoText {
            get {
                return ResourceManager.GetString("StatusBarInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Movies ({1}) of {2} Movies ({3}).
        /// </summary>
        internal static string StatusBarInfoTextFiltered {
            get {
                return ResourceManager.GetString("StatusBarInfoTextFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing File {0} of {1}..
        /// </summary>
        internal static string StatusImportingFile {
            get {
                return ResourceManager.GetString("StatusImportingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to find informations about &apos;{0}&apos;..
        /// </summary>
        internal static string StatusImportingFileContent {
            get {
                return ResourceManager.GetString("StatusImportingFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to find informations about &apos;{0}&apos;..
        /// </summary>
        internal static string StatusSearchingContent {
            get {
                return ResourceManager.GetString("StatusSearchingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in &apos;{0}&apos;..
        /// </summary>
        internal static string StatusSearchingFolder {
            get {
                return ResourceManager.GetString("StatusSearchingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to find all supported media files..
        /// </summary>
        internal static string StatusSearchingFolderContent {
            get {
                return ResourceManager.GetString("StatusSearchingFolderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in {0}..
        /// </summary>
        internal static string StatusSearchingOnline {
            get {
                return ResourceManager.GetString("StatusSearchingOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string StatusWindowTitleImporting {
            get {
                return ResourceManager.GetString("StatusWindowTitleImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening....
        /// </summary>
        internal static string StatusWindowTitleOpening {
            get {
                return ResourceManager.GetString("StatusWindowTitleOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string StatusWindowTitleSearching {
            get {
                return ResourceManager.GetString("StatusWindowTitleSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TASKDIALOG_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("TASKDIALOG_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TASKDIALOG_BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("TASKDIALOG_BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TASKDIALOG_BUTTON_NO {
            get {
                return ResourceManager.GetString("TASKDIALOG_BUTTON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string TASKDIALOG_BUTTON_OK {
            get {
                return ResourceManager.GetString("TASKDIALOG_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TASKDIALOG_BUTTON_YES {
            get {
                return ResourceManager.GetString("TASKDIALOG_BUTTON_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string TASKDIALOG_HIDEDETAILS {
            get {
                return ResourceManager.GetString("TASKDIALOG_HIDEDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Instructions.
        /// </summary>
        internal static string TASKDIALOG_MAININSTRUCTION {
            get {
                return ResourceManager.GetString("TASKDIALOG_MAININSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string TASKDIALOG_SHOWDETAILS {
            get {
                return ResourceManager.GetString("TASKDIALOG_SHOWDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while importing &apos;{0}&apos;!.
        /// </summary>
        internal static string TaskDialogImportFolderExceptionMain {
            get {
                return ResourceManager.GetString("TaskDialogImportFolderExceptionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an Exception while trying to import the file!.
        /// </summary>
        internal static string TaskDialogImportFolderExceptionText {
            get {
                return ResourceManager.GetString("TaskDialogImportFolderExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TaskDialogImportFolderExceptionTitle {
            get {
                return ResourceManager.GetString("TaskDialogImportFolderExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto select first online result?.
        /// </summary>
        internal static string TaskDialogImportingAutoSelectResultMain {
            get {
                return ResourceManager.GetString("TaskDialogImportingAutoSelectResultMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the first result of an online search be selected automaticaly?.
        /// </summary>
        internal static string TaskDialogImportingAutoSelectResultText {
            get {
                return ResourceManager.GetString("TaskDialogImportingAutoSelectResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto select result.
        /// </summary>
        internal static string TaskDialogImportingAutoSelectResultTitle {
            get {
                return ResourceManager.GetString("TaskDialogImportingAutoSelectResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Subfolders as Movies
        ///Imports each Subfolder as a Movie.|Search first Level for files/folders
        ///Folder will be searched for files/folders and also imported.|Search two Levels for files/folders
        ///Folders and their direct subfolders will be searched for files/folders and also imported.|Ignore Folders
        ///Only files direct in the selected folder are imported..
        /// </summary>
        internal static string TaskDialogImportSubFoldersButtons {
            get {
                return ResourceManager.GetString("TaskDialogImportSubFoldersButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Subfolders as Movies?.
        /// </summary>
        internal static string TaskDialogImportSubFoldersMain {
            get {
                return ResourceManager.GetString("TaskDialogImportSubFoldersMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Subfolders are imported as a Movie the name of the Folder is used as Title and the Media-File will link to the folder..
        /// </summary>
        internal static string TaskDialogImportSubFoldersText {
            get {
                return ResourceManager.GetString("TaskDialogImportSubFoldersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Subfolders?.
        /// </summary>
        internal static string TaskDialogImportSubFoldersTitle {
            get {
                return ResourceManager.GetString("TaskDialogImportSubFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media files are offline
        ///Select this to show the stored media properties.|Media files are online
        ///Select this to enter a new media file..
        /// </summary>
        internal static string TaskDialogMediaOfflineButtons {
            get {
                return ResourceManager.GetString("TaskDialogMediaOfflineButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the media file!.
        /// </summary>
        internal static string TaskDialogMediaOfflineMain {
            get {
                return ResourceManager.GetString("TaskDialogMediaOfflineMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media file of this movie can not be found. If you don&apos;t have access to them you can select to only display the media properties stored in the collection..
        /// </summary>
        internal static string TaskDialogMediaOfflineText {
            get {
                return ResourceManager.GetString("TaskDialogMediaOfflineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media file not found.
        /// </summary>
        internal static string TaskDialogMediaOfflineTitle {
            get {
                return ResourceManager.GetString("TaskDialogMediaOfflineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all Web Sources.
        /// </summary>
        internal static string TaskDialogNoOnlineResultsAllSources {
            get {
                return ResourceManager.GetString("TaskDialogNoOnlineResultsAllSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found on {0}!.
        /// </summary>
        internal static string TaskDialogNoOnlineResultsCaption {
            get {
                return ResourceManager.GetString("TaskDialogNoOnlineResultsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on other Web Sources.
        /// </summary>
        internal static string TaskDialogNoOnlineResultsCheckbox {
            get {
                return ResourceManager.GetString("TaskDialogNoOnlineResultsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HINT: May try another Web Source..
        /// </summary>
        internal static string TaskDialogNoOnlineResultsFooter {
            get {
                return ResourceManager.GetString("TaskDialogNoOnlineResultsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found on the selected Web Source with the given name!.
        /// </summary>
        internal static string TaskDialogNoOnlineResultsMain {
            get {
                return ResourceManager.GetString("TaskDialogNoOnlineResultsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        internal static string TaskDialogNoOnlineResultsTitle {
            get {
                return ResourceManager.GetString("TaskDialogNoOnlineResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while searching in {0}!.
        /// </summary>
        internal static string TaskDialogOnlineSearchExceptionMain {
            get {
                return ResourceManager.GetString("TaskDialogOnlineSearchExceptionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an Exception while trying to search the web source!.
        /// </summary>
        internal static string TaskDialogOnlineSearchExceptionText {
            get {
                return ResourceManager.GetString("TaskDialogOnlineSearchExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TaskDialogOnlineSearchExceptionTitle {
            get {
                return ResourceManager.GetString("TaskDialogOnlineSearchExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the development team about this problem.
        ///See the details for the exception details..
        /// </summary>
        internal static string TaskDialogUnhandledExceptionContent {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled Exception occured!.
        /// </summary>
        internal static string TaskDialogUnhandledExceptionMain {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string TaskDialogUnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot:.
        /// </summary>
        internal static string TextBlockPlot {
            get {
                return ResourceManager.GetString("TextBlockPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors are seperated by comma.
        /// </summary>
        internal static string TextBoxDirectorsToolTip {
            get {
                return ResourceManager.GetString("TextBoxDirectorsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here to search....
        /// </summary>
        internal static string TextBoxSearch {
            get {
                return ResourceManager.GetString("TextBoxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Movie.
        /// </summary>
        internal static string ToolBarButtonAdd {
            get {
                return ResourceManager.GetString("ToolBarButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results for &apos;{0}&apos;.
        /// </summary>
        internal static string WebSearchResultTitle {
            get {
                return ResourceManager.GetString("WebSearchResultTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wmv {
            get {
                object obj = ResourceManager.GetObject("wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wmvhd {
            get {
                object obj = ResourceManager.GetObject("wmvhd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x264 {
            get {
                object obj = ResourceManager.GetObject("x264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xvid {
            get {
                object obj = ResourceManager.GetObject("xvid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
