//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCollection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieCollection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string RibbonButtonExit {
            get {
                return ResourceManager.GetString("RibbonButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonButtonSettings {
            get {
                return ResourceManager.GetString("RibbonButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string RibbonGroupLanguage {
            get {
                return ResourceManager.GetString("RibbonGroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RibbonTabFilter {
            get {
                return ResourceManager.GetString("RibbonTabFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string RibbonTabImport {
            get {
                return ResourceManager.GetString("RibbonTabImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonTabSettings {
            get {
                return ResourceManager.GetString("RibbonTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Exception-Details.
        /// </summary>
        internal static string TaskDialogUnhandledExceptionDetailsLabelCollapsed {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionDetailsLabelCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Exception-Details.
        /// </summary>
        internal static string TaskDialogUnhandledExceptionDetailsLabelExpanded {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionDetailsLabelExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled Exception occured!
        ///Please contact the development team about this problem.
        ///See the details for the exception details..
        /// </summary>
        internal static string TaskDialogUnhandledExceptionMain {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By sending us an error report we may can fix that problem in the next version..
        /// </summary>
        internal static string TaskDialogUnhandledExceptionSendButtonInstructions {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionSendButtonInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error-Report.
        /// </summary>
        internal static string TaskDialogUnhandledExceptionSendButtonText {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionSendButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string TaskDialogUnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("TaskDialogUnhandledExceptionTitle", resourceCulture);
            }
        }
    }
}
